server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [".*"]
    
    relabel_configs:
      # Add container name as label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
        
      # Add Docker labels as Loki labels
      - action: labelmap
        regex: __meta_docker_container_label_(.+)
        
      # Add container ID as label
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
        
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
            
      - labels:
          stream:
      
      - timestamp:
          source: time
          format: RFC3339Nano
          
      - output:
          source: log

  - job_name: service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: service-logs
          __path__: /tmp/service-logs/**/*.log
